### ISSUE TITLE
(cercle (position 20 20) 30) au lieu de (cercle (liste 20 20) 30) ?

### ISSUE THREAD

**Issue by juliendorra** [Microalg/microalg#119]
Est-ce que cela aurait du sens d'utiliser

(cercle (position 20 20) 30)

et donc une fonction (position ) au lieu de la fonction générique (liste ) ?

**Comment by Grahack** [comment]
Oups, pas très réactif sur les notifs.
Oui, ça aurait beaucoup de sens en effet, mais si je cède à Position, il faudrait céder à pas mal de choses.
Tu peux toujours définir `Position` toi-même:

    (Definir (Position x y)
      (Retourner (Liste x y))
    )
